version: "3.9"

services:
  web:
    build: .
    container_name: quiz_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - quiz_networks

  db:
    image: postgres:14
    container_name: quiz_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz_networks

volumes:
  postgres_data:

networks:
  quiz_networks:
    name: quiz_networks