version: "3.9"

services:

  test:
    build: .
    container_name: test_app
    command: poetry run pytest -vv
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - test_networks

  db:
    image: postgres:14
    container_name: test_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_networks

volumes:
  postgres_data:

networks:
  test_networks:
    name: test_networks