# Generated by Django 5.2 on 2025-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempt', '0007_alter_quizattempt_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_code',
            field=models.CharField(
                default='EPBUI',
                max_length=7,
                unique=True,
                verbose_name='퀴즈 응시 코드',
            ),
        ),
    ]
