# Generated by Django 5.2 on 2025-04-03 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=255)),
                ('is_random_question', models.BooleanField(default=False)),
                ('is_random_choice', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈',
                'verbose_name_plural': '퀴즈',
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_quizzes', to='question.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': '퀴즈-문제',
                'verbose_name_plural': '퀴즈-문제',
                'db_table': 'quiz_question',
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, through='quiz.QuizQuestion', to='question.question', verbose_name='퀴즈 문제'),
        ),
    ]
