# Generated by Django 5.2 on 2025-04-03 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.PositiveIntegerField(default=0, verbose_name='퀴즈에 노출될 문제 개수'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL, verbose_name='퀴즈 생성한 관리자'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_random_choice',
            field=models.BooleanField(default=False, verbose_name='선택지 랜덤 배치'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_random_question',
            field=models.BooleanField(default=False, verbose_name='문제 랜덤 배치'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='퀴즈 내용'),
        ),
    ]
