# Generated by Django 5.2 on 2025-04-03 00:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('code', models.CharField(default=core.models.generate_code, editable=False, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('code', models.CharField(default=core.models.generate_code, editable=False, unique=True)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='question.question')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지',
                'db_table': 'question_choice',
            },
        ),
    ]
